# -*- coding: utf-8 -*-
"""automate_Fattah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhPSqW5CtlRR6cIjoJ94wcN5LuaOxnS_
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os


def preprocess_data(
    input_path,
    output_path,
    target_column
):
    # Load dataset
    df = pd.read_csv(input_path)

    # Remove duplicates
    df = df.drop_duplicates()

    # Remove missing values
    df = df.dropna()

    # Feature-target split
    X = df.drop(columns=[target_column])
    y = df[target_column]

    # Scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Rebuild dataframe
    processed_df = pd.DataFrame(X_scaled, columns=X.columns)
    processed_df[target_column] = y.values

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Save processed dataset
    processed_df.to_csv(output_path, index=False)

    return processed_df

    if __name__ == "__main__":
    preprocess_data(
        input_path="data/raw/home_value_insights.csv",
        output_path="data/processed/processed_data.csv",
        target_column="Price"
    )